db:
  username: postgres
  password: qaZwsX.1001
  driver: PostgresDriver
  url: postgres:5432
  host: localhost
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
#spring.profiles.active:qa